import { defineConfig } from "oxlint";

export default defineConfig({
   plugins: ["import", "typescript"],
   categories: {
      correctness: "off",
   },
   options: {
      typeAware: true,
   },
   env: {
      builtin: true,
   },
   ignorePatterns: ["**/vite.config.*.timestamp-*.*", ".output/*", "migrations/**"],
   rules: {
      "@logtape/no-message-interpolation": "error",
      "@logtape/prefer-lazy-evaluation": "warn",
      "@logtape/no-unawaited-log": "error",
      "@logtape/require-meta-sink": "warn",
   },
   jsPlugins: [{ name: "@logtape", specifier: "@logtape/lint/eslint" }],
   overrides: [
      {
         files: ["**/*.{js,ts,tsx}"],
         rules: {
            "for-direction": "error",
            "no-async-promise-executor": "error",
            "no-case-declarations": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-constant-binary-expression": "error",
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-dupe-else-if": "error",
            "no-duplicate-case": "error",
            "no-empty-character-class": "error",
            "no-empty-pattern": "error",
            "no-empty-static-block": "error",
            "no-ex-assign": "error",
            "no-extra-boolean-cast": "error",
            "no-fallthrough": "error",
            "no-global-assign": "error",
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-loss-of-precision": "error",
            "no-misleading-character-class": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-regex-spaces": "error",
            "no-self-assign": "error",
            "no-shadow": "warn",
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-labels": "error",
            "no-unused-private-class-members": "error",
            "no-useless-backreference": "error",
            "no-useless-catch": "error",
            "no-useless-escape": "error",
            "no-var": "error",
            "no-with": "error",
            "prefer-const": "error",
            "require-yield": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            "@typescript-eslint/ban-ts-comment": [
               "error",
               {
                  "ts-expect-error": false,
                  "ts-ignore": "allow-with-description",
               },
            ],
            "@typescript-eslint/consistent-type-imports": [
               "error",
               {
                  prefer: "type-imports",
               },
            ],
            "@typescript-eslint/no-duplicate-enum-values": "error",
            "@typescript-eslint/no-extra-non-null-assertion": "error",
            "@typescript-eslint/no-for-in-array": "error",
            "@typescript-eslint/no-inferrable-types": [
               "error",
               {
                  ignoreParameters: true,
               },
            ],
            "@typescript-eslint/no-misused-new": "error",
            "@typescript-eslint/no-namespace": "error",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
            "@typescript-eslint/no-unnecessary-condition": "error",
            "@typescript-eslint/no-unnecessary-type-assertion": "error",
            "@typescript-eslint/no-unsafe-function-type": "error",
            "@typescript-eslint/no-wrapper-object-types": "error",
            "@typescript-eslint/prefer-as-const": "error",
            "@typescript-eslint/prefer-for-of": "warn",
            "@typescript-eslint/require-await": "warn",
            "@typescript-eslint/triple-slash-reference": "error",
            "import/first": "error",
            "import/no-commonjs": "error",
            "import/no-duplicates": "error",
            "@stylistic/spaced-comment": "error",
         },
         jsPlugins: ["@stylistic/eslint-plugin"],
         env: {
            es2020: true,
            browser: true,
         },
      },
   ],
});
